/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CPU */

#ifndef _Included_CPU
#define _Included_CPU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CPU
 * Method:    get
 * Signature: ()LCPU;
 */
JNIEXPORT jobject JNICALL Java_CPU_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
